#!/usr/bin/env python3
"""Write src/shared/HubLayout.luau from assets/hub/Markers.json.

The hub package (assets/hub, built by HubBuilder.py) records where every prop copy, seat, light
and collision box goes. The game reads this generated module at run time (server HubService).
Everything is in Roblox world studs; the hub's origin is the room centre on the main floor.

Run from the repo root after re-exporting the hub:  python3 tools/gen_hub_layout.py
then tools/format.sh (StyLua lays the file out).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
MARKERS = os.path.join(REPO, 'assets', 'hub', 'Markers.json')
OUT = os.path.join(REPO, 'src', 'shared', 'HubLayout.luau')


def num(v):
    v = round(float(v), 3) + 0.0
    return ('%d' % v) if v == int(v) else ('%s' % v)


def vec(v):
    return ', '.join(num(c) for c in v)


def main():
    m = json.load(open(MARKERS))
    out = ['--!strict',
           '-- GENERATED by tools/gen_hub_layout.py from assets/hub/Markers.json. Do not edit by hand:',
           '-- re-export the hub (assets/hub/HubBuilder.py -- export) and run the generator again.',
           '-- Roblox world studs; the hub origin is the room centre on the main floor. yaw is degrees',
           '-- about +Y (CFrame.Angles(0, math.rad(yaw), 0)). Read by the server HubService.',
           '',
           'export type Placement = { prop: string, x: number, y: number, z: number, yaw: number,',
           '\tsx: number, sy: number, sz: number, tint: string?, name: string? }',
           'export type Seat = { x: number, y: number, z: number, yaw: number }',
           'export type Light = { name: string, kind: string, x: number, y: number, z: number,',
           '\tdx: number, dy: number, dz: number, w: number, d: number, colour: string, brightness: number,',
           '\trange: number, angle: number, shadows: boolean }',
           'export type Box = { name: string, shape: string, x: number, y: number, z: number,',
           '\tsx: number, sy: number, sz: number, rises: string? }',
           'export type Anchor = { x: number, y: number, z: number, yaw: number }',
           '',
           'local Layout = {}',
           '']
    # prop masters: which meshes in ServerStorage.Hub_PropLibrary make up each prop
    out.append('-- Each prop is these meshes of the library, cloned together. tint: its fabric takes the')
    out.append('-- placement\'s colour (SurfaceAppearance.Color).')
    out.append('Layout.Masters = {')
    for name, rec in sorted(m['props']['masters'].items()):
        parts = ', '.join('"%s"' % p for p in sorted(rec['parts']))
        out.append('\t%s = { parts = { %s }, tint = %s },' % (name, parts, 'true' if rec['tint'] else 'false'))
    out.append('} :: { [string]: { parts: { string }, tint: boolean } }')
    out.append('')
    out.append('Layout.Placements = {')
    for p in m['props']['placements']:
        s = p['scale']  # Blender axes (x, y, z) -> Roblox (x, z, y)
        x, y, z = p['position']
        fields = ['prop = "%s"' % p['prop'], 'x = %s' % num(x), 'y = %s' % num(y), 'z = %s' % num(z),
                  'yaw = %s' % num(p['yaw_deg']), 'sx = %s' % num(s[0]), 'sy = %s' % num(s[2]),
                  'sz = %s' % num(s[1])]
        if p.get('tint'):
            fields.append('tint = "%s"' % p['tint'])
        if p.get('table'):
            fields.append('name = "Pendant_T%s"' % p['table'].split('_')[1])
        out.append('\t{ %s },' % ', '.join(fields))
    out.append('} :: { Placement }')
    out.append('')
    out.append('-- Sittable spots (the seat surface) and the way a sitter faces.')
    out.append('Layout.Seats = {')
    for st in m['seats']:
        x, y, z = st['position']
        out.append('\t{ x = %s, y = %s, z = %s, yaw = %s },' % (num(x), num(y), num(z), num(st['yaw_deg'])))
    out.append('} :: { Seat }')
    out.append('')
    out.append('-- The lights (assets/hub/Readme.md, Lights). w and d are a SurfaceLight\'s glowing face.')
    out.append('Layout.Lights = {')
    for li in m['lights']:
        x, y, z = li['position']
        dx, dy, dz = li.get('direction', [0, -1, 0])
        w, d = li.get('face_size', [0.5, 0.5])
        out.append('\t{ name = "%s", kind = "%s", x = %s, y = %s, z = %s, dx = %s, dy = %s, dz = %s, w = %s, d = %s, '
                   'colour = "%s", brightness = %s, range = %s, angle = %s, shadows = %s },'
                   % (li['name'], li['type'], num(x), num(y), num(z), num(dx), num(dy), num(dz), num(w), num(d),
                      li['colour'], num(li['brightness']), num(li['range']), num(li.get('angle', 90)),
                      'true' if li.get('shadows') else 'false'))
    out.append('} :: { Light }')
    out.append('')
    out.append('-- Invisible collision: boxes and one wedge (the stair ramp, rising towards `rises`).')
    out.append('Layout.Collision = {')
    for c in m['collision']:
        x, y, z = c['centre']
        sx, sy, sz = c['size']
        extra = ', rises = "%s"' % c['rises_towards'] if c.get('rises_towards') else ''
        out.append('\t{ name = "%s", shape = "%s", x = %s, y = %s, z = %s, sx = %s, sy = %s, sz = %s%s },'
                   % (c['name'], c['shape'], num(x), num(y), num(z), num(sx), num(sy), num(sz), extra))
    out.append('} :: { Box }')
    out.append('')
    out.append('-- Named anchors for what the game places or swaps later (statues, decor, secrets, ...).')
    out.append('Layout.Anchors = {')
    for name, a in sorted(m['anchors'].items()):
        if name.startswith(('Seat_', 'Pad_')):
            continue
        x, y, z = a['position']
        out.append('\t%s = { x = %s, y = %s, z = %s, yaw = %s },' % (name, num(x), num(y), num(z), num(a['yaw_deg'])))
    out.append('} :: { [string]: Anchor }')
    out.append('')
    out.append('return Layout')
    with open(OUT, 'w') as f:
        f.write('\n'.join(out) + '\n')
    print('wrote', OUT, len(m['props']['placements']), 'placements', len(m['seats']), 'seats',
          len(m['lights']), 'lights', len(m['collision']), 'boxes')


if __name__ == '__main__':
    main()
