#!/usr/bin/env python3
"""Write assets/balls/ball_sphere.obj: a smooth UV sphere (radius 1) with equirectangular
UVs that match tools/gen_ball_textures.py. Import it once in Studio (3D Importer, Scale
Unit: Stud), move the MeshPart to ServerStorage.BallMesh and save the place.

Longitude runs around Y (up); u = 0.5 at +X, increasing towards +Z. v = 1 at the top.
"""
import math
import os

SEGMENTS = 48  # around
RINGS = 24  # top to bottom
OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "balls", "ball_sphere.obj")


def main():
    verts, uvs, norms, faces = [], [], [], []
    for r in range(RINGS + 1):
        lat = math.pi / 2 - math.pi * r / RINGS
        y = math.sin(lat)
        c = math.cos(lat)
        for s in range(SEGMENTS + 1):
            lon = 2 * math.pi * (s / SEGMENTS - 0.5)
            x, z = c * math.cos(lon), c * math.sin(lon)
            verts.append((x, y, z))
            norms.append((x, y, z))
            uvs.append((s / SEGMENTS, 1 - r / RINGS))
    cols = SEGMENTS + 1
    for r in range(RINGS):
        for s in range(SEGMENTS):
            a = r * cols + s + 1  # obj indices are 1-based
            b = a + 1
            c = a + cols
            d = c + 1
            if r > 0:
                faces.append((a, c, b))
            if r < RINGS - 1:
                faces.append((b, c, d))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# 8ball sphere, generated by tools/gen_ball_mesh.py\n")
        f.write("o BallMesh\n")
        for v in verts:
            f.write("v %.6f %.6f %.6f\n" % v)
        for t in uvs:
            f.write("vt %.6f %.6f\n" % t)
        for n in norms:
            f.write("vn %.6f %.6f %.6f\n" % n)
        f.write("s 1\n")
        for a, b, c in faces:
            f.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % (a, a, a, b, b, b, c, c, c))
    print(f"wrote {os.path.abspath(OUT)}: {len(verts)} vertices, {len(faces)} triangles")


if __name__ == "__main__":
    main()
